title: Open School Brasil
description: Uma escola aberta, da comunidade, para a comunidade!
email: openschoolbr@gmail.com
user: openschoolbr
baseurl: ""

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/_sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
